camera_subscriber: force queue_size to 1 for each subscriber
ros-perception/image_common pull request #123
Opened 2019-03-14 04:33 UTC by furushchev

There is no need to cache data in each subscriber on synchronization.

2023-12-19 19:40 UTC, furushchev commented
@clalancette @ahcorde Kindly ping to the maintainers. It will increase the chance that the callback function is called even when there is a large difference in the publishing frequency between the image and camera info topics.

2023-12-27 17:49 UTC, furushchev commented
@clalancette @ahcorde Kindly ping to the maintainers...

2024-01-18 12:10 UTC, ahcorde approved these changes
@clalancette want do you think ?

2025-04-08 20:53 UTC, furushchev commented
@clalancette @ahcorde Thank you for the review. Any chance this pull request is merged?
I believe there is only a downside to miss some received messages without this change.

2025-04-22 21:53 UTC, sloretz requested changes
Thank you for the PR and your patience @furushchev !

I don't think we should take this PR this close to [ROS Noetic end of life](https://discourse.ros.org/t/ros-noetic-end-of-life-may-31-2025/43160). Changing queue_size significantly changes behavior. Users cannot go back to the old behavior because AFAIK ROS 1 does not have a way to override the queue_size setting at runtime like ROS 2 does with it's QoS overrides.

2025-04-22 21:54 UTC, sloretz commented
I'm going to close this one as not-planned.

2025-04-22 21:54 UTC, closed without merging