Add optional namespace to /set_camera_info service in CameraInfoManager
ros-perception/image_common pull request #324
Opened 2024-09-24 14:01 UTC by jasiex01

Hi,
In the quite common case that one node serves two cameras and where each camera has its own `CameraInfoManager,` there will only be one `/set_camera_info` service that will update both .yaml files which is not ideal. 
Up until Humble this could have been remedied by using a sub-node with its custom namespace, however since updating the code to work with lifecycle nodes this is not possible anymore.

I have added a `ns` parameter to `CameraInfoManager` constructors that will be added as a prefix to the `/set_camera_info` service during its creation. As the parameter is optional, without specyfing it `CameraInfoManager` will act as before - the string passed during the creation of the service will be `~/set_camera_info`. This ensures backwards compatibility and would not require anybody to modify their code and this would allow bigger control for users over the name of the service.

2024-09-24 20:30 UTC, ahcorde requested changes
We cannot backport this PR as it is, the PR breaks ABI, the signature of the constructor has changed

2024-09-24 20:30 UTC, ahcorde commented on camera_info_manager/include/camera_info_manager/camera_info_manager.hpp
>      rmw_qos_profile_t custom_qos = rmw_qos_profile_default);
This way we will not break other user 
```suggestion
    const std::string & cname = "camera", const std::string & url = "",
    rmw_qos_profile_t custom_qos = rmw_qos_profile_default,
    const std::string & ns = "~");
```

2024-09-25 12:05 UTC, jasiex01 commented
Fixed the attribute order

2024-09-25 16:28 UTC, ahcorde approved these changes

2024-09-25 16:29 UTC, ahcorde commented
Pulls: ros-perception/image_common#324
Gist: https://gist.githubusercontent.com/ahcorde/5b8d0bdeb61f02dae474e0e360299b85/raw/3986349c5c747dbb3422ad5cc8b00f3dcad84368/ros2.repos
BUILD args:   --packages-above-and-dependencies camera_info_manager --packages-above-and-dependencies camera_info_manager
TEST args:  --packages-above camera_info_manager --packages-above camera_info_manager
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14612
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21893)](http://ci.ros2.org/job/ci_linux/21893/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16161)](http://ci.ros2.org/job/ci_linux-aarch64/16161/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1402)](http://ci.ros2.org/job/ci_linux-rhel/1402/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22611)](http://ci.ros2.org/job/ci_windows/22611/)

2024-09-25 19:42 UTC, merged